plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.mudai.ytm_listener'
    compileSdk 34

    defaultConfig {
        applicationId "com.mudai.ytm_listener"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // HTTP通信用のOkHttp
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    
    // JSON解析用のGson
    implementation 'com.google.code.gson:gson:2.10.1'

    // 非同期処理用のCoroutine
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
}
